// Test generated by RoostGPT for test uploadfilespringboot using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class NotFoundException_NotFoundException_b5f83317fb_Test {

    private NotFoundException notFoundException;

    @BeforeEach
    public void setup() {
        notFoundException = new NotFoundException();
    }

    @Test
    public void testNotFoundExceptionMessage() {
        assertEquals("Not Found", notFoundException.getMessage());
    }

    @Test
    public void testNotFoundExceptionInstanceOfException() {
        assertTrue(notFoundException instanceof Exception);
    }
}
