// Test generated by RoostGPT for test uploadfilespringboot using AI Type Open AI and AI Model gpt-4

package com.company.internationalizationtaticfilesandresources.controller;

import com.company.internationalizationtaticfilesandresources.service.FileStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;
import java.nio.file.Path;
import java.util.stream.Stream;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class FileController_getFile_7a9b8d2dbd_Test {

    @Mock
    private FileStorageService fileStorageService;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetFileSuccess() {
        Stream<Path> expectedStream = Stream.of(Path.of("/file1"), Path.of("/file2"));
        when(fileStorageService.getFilesStream()).thenReturn(expectedStream);

        ResponseEntity<Stream<Path>> response = getFile();
        assertEquals(ResponseEntity.ok(expectedStream), response);
    }

    @Test
    public void testGetFileFailure() {
        when(fileStorageService.getFilesStream()).thenThrow(new RuntimeException());

        ResponseEntity<Stream<Path>> response = getFile();
        assertEquals(ResponseEntity.status(500).build(), response);
    }

    private ResponseEntity<Stream<Path>> getFile() {
        try {
            return ResponseEntity.ok(fileStorageService.getFilesStream());
        } catch (Exception e) {
            return ResponseEntity.status(500).build();
        }
    }
}
